### PR TITLE
Add option to silence printing of stacktraces

### PR DESCRIPTION
**Pull request by gratimax**
This is a fantastic library, thanks for writing it. However, in development I use this in conjunction with a logging middleware which already handles printing exceptions to the command line. It's a really small issue, but I would prefer that prone wouldn't log exceptions in this case, and so I added an option to silence it. I'm not quite sure how to test this, but I did verify it locally.

### CODE REVIEW

**Comment by magnars** [comment]
Good call, thanks! 

One thing: a `nil` value is now truthy for `:print-stacktraces?`. That doesn't feel so good. Maybe use `(:print-stacktraces? opts true)` instead?

**Comment by gratimax** [comment]
Hmm, that makes sense. Another option is to add an `:or {:print-stacktraces? true}` when destructuring the option map, that seems to be a bit cleaner to me. What do you think?

**Comment by magnars** [comment]
Yep, that works too. :)

fre. 18. mar. 2016 kl. 16.08 skrev Max Ovsiankin <notifications@github.com>:

**Comment by gratimax** [comment]
Finished the changes

**Comment by magnars** [comment]
Looking good :+1:

**Comment by magnars** [comment]
`1.1.0` released with this fix.

**Pull request merged**
